/**
 * A structured object containing file paths to all game image assets.
 *
 * Images are grouped by categories like landscape, characters, items, etc.
 * This object is used for preloading and assigning image assets.
 *
 * @type {Object.<string, Object.<string, string>>}
 */
const IMAGE_PATHS = {
    landscape: {
      backgrounds: './assets/img/background/01/layers/l1-background.png',
      fog: './assets/img/background/01/layers/l3-fog.png',
      stars: './assets/img/background/01/layers/l4-stars01.png',
      northern_lights_1: './assets/img/background/01/layers/l2-northern-lights01.png',
      northern_lights_2: './assets/img/background/01/layers/l5-northern-lights02.png',
      mountains_7: './assets/img/background/01/layers/l7-mountains01.png',
      mountains_8: './assets/img/background/01/layers/l8-mountains01.png',
      ground_1: './assets/img/background/01/layers/l9-ground01.png',
      ground_2: './assets/img/background/01/layers/l9-ground02.png',
      moon: './assets/img/background/01/layers/l6-moon.png',
    },
    penguin: {
      walk: [
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_00.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_02.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_04.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_06.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_08.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_10.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_12.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_14.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_16.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_18.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_20.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_22.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_24.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_26.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_28.png',
        './assets/img/Penguin/Character09/Walk/AllCharacters-Character09-Walk_29.png',
        ,
      ],
      jump: [
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_00.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_01.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_02.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_03.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_04.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_05.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_06.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_07.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_08.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_09.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_10.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_11.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_12.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_13.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_14.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_15.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_16.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_17.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_18.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_19.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_20.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_21.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_22.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_23.png',
        './assets/img/Penguin/Character09/Jump/AllCharacters-Character09-Jump_24.png',
      ],
      hurt: [
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_00.png',
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_02.png',
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_04.png',
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_06.png',
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_08.png',
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_10.png',
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_12.png',
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_14.png',
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_16.png',
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_18.png',
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_20.png',
        './assets/img/Penguin/Character09/Confused/All Characters-Character09-Confused_22.png',
      ],
      idle: [
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_00.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_01.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_02.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_03.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_04.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_05.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_06.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_07.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_08.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_09.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_10.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_11.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_12.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_13.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_14.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_15.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_16.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_17.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_18.png',
        './assets/img/Penguin/Character09/Idle/AllCharacters-Character09-Idle_19.png',
      ],
      dead: [
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_00.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_02.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_04.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_06.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_08.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_10.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_12.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_14.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_16.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_18.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_20.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_22.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_24.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_26.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_28.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_30.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_32.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_34.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_36.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_38.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_40.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_42.png',
        './assets/img/Penguin/Character09/Dead/AllCharacters-Character09-Dead_44.png',
      ],
      sleep: './assets/img/Penguin/Character09/Sleeping/AllCharacters-Character09-Sleep_00.png',
    },
    rabbits: {
      walk: [
        './assets/img/Rabbit/Monster5/Moving/Moving_00.png',
        './assets/img/Rabbit/Monster5/Moving/Moving_02.png',
        './assets/img/Rabbit/Monster5/Moving/Moving_04.png',
        './assets/img/Rabbit/Monster5/Moving/Moving_06.png',
        './assets/img/Rabbit/Monster5/Moving/Moving_08.png',
        './assets/img/Rabbit/Monster5/Moving/Moving_10.png',
        './assets/img/Rabbit/Monster5/Moving/Moving_12.png',
        './assets/img/Rabbit/Monster5/Moving/Moving_14.png',
        './assets/img/Rabbit/Monster5/Moving/Moving_16.png',
        './assets/img/Rabbit/Monster5/Moving/Moving_18.png',
        './assets/img/Rabbit/Monster5/Moving/Moving_19.png',
      ],
    },
    endboss: {
      walk: [
        './assets/img/Enemy/Walking/0_Elementals_Walking_000.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_001.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_002.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_003.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_004.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_005.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_006.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_007.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_008.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_009.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_010.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_011.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_012.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_013.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_014.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_015.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_016.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_017.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_018.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_019.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_020.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_021.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_022.png',
        './assets/img/Enemy/Walking/0_Elementals_Walking_023.png',
      ],
      hurt: [
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_000.png',
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_001.png',
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_002.png',
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_003.png',
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_004.png',
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_005.png',
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_006.png',
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_007.png',
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_008.png',
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_009.png',
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_010.png',
        './assets/img/Enemy/Hurt/0_Elementals_Hurt_011.png',
      ],
      dead: [
        './assets/img/Enemy/Dying/0_Elementals_Dying_000.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_001.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_002.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_003.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_004.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_005.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_006.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_007.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_008.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_009.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_010.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_011.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_012.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_013.png',
        './assets/img/Enemy/Dying/0_Elementals_Dying_014.png',
      ],
      status_bar_hearts: [
        './assets/img/Enemy/heartEndboss.png',
        './assets/img/Enemy/heartEndboss.png',
        './assets/img/Enemy/heartEndboss.png',
        './assets/img/Enemy/heartEndboss.png',
        './assets/img/Enemy/heartEndboss.png'
      ],
      status_bar_broken_heart: './assets/img/Enemy/heartEndbossLost.png',
    },
    coin: './assets/img/Coins/1.png',
    status_bar_coin: [
      './assets/img/StatusBarCoin/0_ _1.png',
      './assets/img/StatusBarCoin/20_ .png',
      './assets/img/StatusBarCoin/40_ _1.png',
      './assets/img/StatusBarCoin/60_ _1.png',
      './assets/img/StatusBarCoin/80_ _1.png',
      './assets/img/StatusBarCoin/100__1.png',
    ],
    heart: './assets/img/Heart/heart1.png',
    status_bar_hearts: [
      './assets/img/StatusBarHeart/0_ .png',
      './assets/img/StatusBarHeart/20__1.png',
      './assets/img/StatusBarHeart/40_ .png',
      './assets/img/StatusBarHeart/60_ .png',
      './assets/img/StatusBarHeart/80_ .png',
      './assets/img/StatusBarHeart/100_ .png',
    ],
    poison: {
      poison_left: './assets/img/Poison/Dark-Left.png',
      poison_right: './assets/img/Poison/Dark-Right.png',
    },
    status_bar_poison: [
      './assets/img/StatusBarBottle/0_.png',
      './assets/img/StatusBarBottle/20_.png',
      './assets/img/StatusBarBottle/40_.png',
      './assets/img/StatusBarBottle/60_.png',
      './assets/img/StatusBarBottle/80_.png',
      './assets/img/StatusBarBottle/100_.png'
    ]
  };